/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_mp5lstreamdecoder_free: (a: number, b: number) => void;
export const __wbg_mp5lv4streamencoder_free: (a: number, b: number) => void;
export const assemble_mp5l_v4: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const decode_mp5c: (a: number, b: number) => [number, number, number, number];
export const decode_mp5c3: (a: number, b: number) => [number, number, number, number];
export const decode_mp5c6: (a: number, b: number) => [number, number, number, number];
export const decode_mp5c6_range: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decode_mp5c_vnext: (a: number, b: number) => [number, number, number, number];
export const decode_mp5h: (a: number, b: number, c: number) => [number, number, number, number];
export const decode_mp5l: (a: number, b: number) => [number, number, number, number];
export const encode_mp5c: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5c3: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5c6: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const encode_mp5c6_at: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const encode_mp5c6_opt: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const encode_mp5c6_vbr: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const encode_mp5c_vnext: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5c_vnext_at: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const encode_mp5c_vnext_legacy_loud: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5c_vnext_mdct: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5c_vnext_protect: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const encode_mp5c_vnext_protect_at: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const encode_mp5h: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5h_min: (a: number, b: number, c: number, d: number) => [number, number];
export const encode_mp5l: (a: number, b: number, c: number) => [number, number];
export const encode_mp5l_v4: (a: number, b: number, c: number) => [number, number];
export const encode_mp5l_v4_frame: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const inspect_unit_mix: (a: number, b: number) => [number, number, number, number];
export const mp5lstreamdecoder_new: (a: number, b: number) => [number, number, number];
export const mp5lstreamdecoder_push: (a: number, b: number, c: number) => [number, number, number, number];
export const mp5lstreamdecoder_push_until: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const mp5lstreamdecoder_seek_frame: (a: number, b: number) => [number, number];
export const mp5lv4streamencoder_encodeNextFrame: (a: number) => number;
export const mp5lv4streamencoder_finish: (a: number) => [number, number];
export const mp5lv4streamencoder_frameCount: (a: number) => number;
export const mp5lv4streamencoder_framesDone: (a: number) => number;
export const mp5lv4streamencoder_new: (a: number, b: number, c: number) => number;
export const nmr_screen_wasm: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const plan_mp5l_v4_boundaries: (a: number, b: number, c: number) => [number, number];
export const snr_db_wasm: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
