// MP5 Audio Quality Lab — .mp5 inspection, file comparison, and hiss reporting.
//
// Reference (typically MP5-L lossless) is treated as ground-truth PCM; candidates
// are scored against it. All decode goes through the mp5file.mjs contract
// (trim-to-totalSamples), proven by selfTest() before any numbers are trusted.
import { basename } from "node:path";
import { statSync } from "node:fs";
import { decodeMp5FileToPcm, inspectParsed, parseMp5File } from "./mp5file.mjs";
import { computeMetrics } from "./metrics.mjs";
import { hissMetrics, hissRisk, HISS_RISK_THRESHOLDS } from "./hiss.mjs";
import { vnextFallbackStats, VNEXT_PARAMS } from "./codecs.mjs";

const RISK_ICON = { low: "🟢 low", medium: "🟡 medium", high: "🟠 high", severe: "🔴 severe", "n/a": "—" };

function num(v, d = 1) {
  if (v === null || v === undefined) return "—";
  if (v === "inf") return "∞";
  return typeof v === "number" ? v.toFixed(d) : String(v);
}

/** Structural inspection of .mp5 files (no scoring). Paths shown as basenames. */
export function inspectFiles(codec, paths) {
  return paths.map((p) => {
    const parsed = parseMp5File(p);
    const insp = inspectParsed(parsed, statSync(p).size);
    let decodeOk = false;
    let decodedSamples = 0;
    try {
      const d = decodeMp5FileToPcm(codec, p);
      decodeOk = true;
      decodedSamples = d.samples.length;
    } catch (e) {
      insp.decodeError = String(e.message ?? e);
    }
    return { file: basename(p), decodeOk, decodedSamples, ...insp };
  });
}

export function writeInspectReport(entries) {
  let md = "# IS THIS A CULT? — local reference inspection\n\n";
  md += "_Local-only, git-ignored. Generated by `audio:inspect`. Track titles may appear; absolute paths are not recorded._\n\n";
  md += "| File | Codec | v | Preset | ch | SR | Frames | Dur (s) | Size (MB) | ×PCM | CORR (MB) | Bit-exact? | Decode |\n";
  md += "|------|-------|--:|-------:|--:|---:|-------:|--------:|----------:|-----:|----------:|:----------:|:------:|\n";
  for (const e of entries) {
    md += `| ${e.file} | ${e.codecName} | ${e.bitstreamVersion ?? "—"} | ${e.presetId ?? "—"} | ${e.channels} | ${e.sampleRate} | ${e.totalFrames} | ${e.durationSec.toFixed(1)} | ${(e.fileSizeBytes / 1048576).toFixed(2)} | ${num(e.ratioVsPcm, 3)} | ${(e.corrBytes / 1048576).toFixed(2)} | ${e.expectedBitExact ? "yes" : "no"} | ${e.decodeOk ? "ok" : "FAIL"} |\n`;
  }
  md += "\n## Notes\n\n";
  md += "- MP5-H tracks carry a large CORR layer; with CORR applied they reconstruct sample-exact content but the file is much larger than MP5-L.\n";
  md += "- MP5-C ratios at or above MP5-L mean the lossy stream is no smaller than the lossless one on this material.\n";
  return md;
}

/**
 * Compare candidate .mp5 files against a reference .mp5 (decoded to PCM).
 * Returns { reference, candidates: [...] }. Skips on SR/channel mismatch
 * (no resampler in the repo).
 */
export function compareFiles(codec, refPath, candPaths) {
  const ref = decodeMp5FileToPcm(codec, refPath);
  const refSize = statSync(refPath).size;
  const reference = {
    file: basename(refPath),
    codec: ref.codecName,
    channels: ref.channels,
    sampleRate: ref.sampleRate,
    frames: ref.totalFrames,
    sizeBytes: refSize,
    decodePath: ref.decodePath,
  };
  const candidates = candPaths.map((p) => {
    const size = statSync(p).size;
    let cand;
    try {
      cand = decodeMp5FileToPcm(codec, p);
    } catch (e) {
      return { file: basename(p), error: String(e.message ?? e) };
    }
    if (cand.sampleRate !== ref.sampleRate || cand.channels !== ref.channels) {
      return {
        file: basename(p),
        codec: cand.codecName,
        skipped: `sample-rate/channel mismatch (ref ${ref.sampleRate}/${ref.channels} vs ${cand.sampleRate}/${cand.channels}) — no resampler; comparison skipped`,
        sizeBytes: size,
      };
    }
    const m = computeMetrics(ref.samples, cand.samples, ref.channels, ref.sampleRate);
    const h = hissMetrics(ref.samples, cand.samples, ref.channels, ref.sampleRate);
    const risk = hissRisk({
      quietWindowSnrDb: m.quietWindowSnrDb,
      tailSnrDb: h.tailSnrDb,
      worstQuiet1sSnrDb: h.worstQuiet1sSnrDb,
      bitExact: m.contentBitExact,
    });
    return {
      file: basename(p),
      codec: cand.codecName,
      decodePath: cand.decodePath,
      sizeBytes: size,
      sizeVsRef: size / refSize,
      sampleMatch: cand.samples.length === ref.samples.length,
      metrics: m,
      hiss: h,
      hissRisk: risk,
    };
  });
  return { reference, candidates, thresholds: HISS_RISK_THRESHOLDS };
}

export function writeCompareReport({ reference, candidates }) {
  let md = "# MP5 file comparison vs reference\n\n";
  md += `_Local/git-ignored. Reference (ground truth): **${reference.file}** (${reference.codec}, ${reference.channels}ch @ ${reference.sampleRate}Hz, ${reference.frames} frames, ${(reference.sizeBytes / 1048576).toFixed(2)} MB)._\n\n`;
  md += "Hiss Risk uses quiet-class SNR thresholds: low ≥40dB · medium ≥25 · high ≥12 · severe <12.\n\n";
  md += "| Candidate | Codec | Size MB | ×Ref | Full SNR | Quiet SNR | Tail SNR | Worst-1s quiet | HF floor dBFS | Err flatness | Clip | Hiss risk |\n";
  md += "|-----------|-------|--------:|-----:|---------:|----------:|---------:|---------------:|--------------:|-------------:|-----:|:---------:|\n";
  for (const c of candidates) {
    if (c.error) { md += `| ${c.file} | — | — | — | decode error: ${c.error} |||||||\n`; continue; }
    if (c.skipped) { md += `| ${c.file} | ${c.codec} | ${(c.sizeBytes / 1048576).toFixed(2)} | — | ${c.skipped} |||||||\n`; continue; }
    const m = c.metrics, h = c.hiss;
    md += `| ${c.file} | ${c.codec} | ${(c.sizeBytes / 1048576).toFixed(2)} | ${num(c.sizeVsRef, 3)} | ${num(m.fullSnrDb)} | ${num(m.quietWindowSnrDb)} | ${num(h.tailSnrDb)} | ${num(h.worstQuiet1sSnrDb)} | ${num(h.hfNoiseFloorDbfs)} | ${num(h.errorSpectralFlatness, 3)} | ${m.clippingCount} | ${RISK_ICON[c.hissRisk] ?? c.hissRisk} |\n`;
  }
  md += "\n_Full-song SNR is shown but is misleading on its own; judge hiss by quiet/tail SNR + HF floor + error flatness (broadband error = hiss)._\n";
  return md;
}

/** Synthetic-fixture hiss matrix rows (computeMetrics + hissMetrics + risk). */
export function buildHissRows(fixtures, modes) {
  const rows = [];
  for (const fx of fixtures) {
    const pcmBytes = fx.samples.length * 2;
    for (const mode of modes) {
      let enc, dec;
      try {
        enc = mode.encode(fx.samples, fx.channels);
        dec = mode.decode(enc);
      } catch (e) {
        rows.push({ fixture: fx.name, mode: mode.id, error: String(e) });
        continue;
      }
      const m = computeMetrics(fx.samples, dec, fx.channels, fx.sampleRate);
      const h = hissMetrics(fx.samples, dec, fx.channels, fx.sampleRate);
      const risk = hissRisk({
        quietWindowSnrDb: m.quietWindowSnrDb,
        tailSnrDb: h.tailSnrDb,
        worstQuiet1sSnrDb: h.worstQuiet1sSnrDb,
        bitExact: m.contentBitExact,
      });
      const fb = mode.id.startsWith("mp5c2") ? vnextFallbackStats(enc) : null;
      rows.push({
        fixture: fx.name,
        mode: mode.id,
        label: mode.label,
        ratioVsPcm: enc.length / pcmBytes,
        fullSnrDb: m.fullSnrDb,
        quietWindowSnrDb: m.quietWindowSnrDb,
        tailSnrDb: h.tailSnrDb,
        worstQuiet1sSnrDb: h.worstQuiet1sSnrDb,
        hfNoiseFloorDbfs: h.hfNoiseFloorDbfs,
        errorSpectralFlatness: h.errorSpectralFlatness,
        contentBitExact: m.contentBitExact,
        hissRisk: risk,
        protectedSamplePct: fb ? fb.protectedSamplePct : null,
        bandQuietSamplePct: fb ? fb.bandQuietSamplePct : null,
      });
    }
  }
  return rows;
}

export function writeHissReport({ generatedAt, rows, referenceResult }) {
  // TL;DR: best new vNext (sub-block+band) vs current MP5-C AND vs previous vNext.
  const find = (fx, mode) => rows.find((r) => r.fixture === fx && r.mode === mode);
  const q = (r) => (r && typeof r.quietWindowSnrDb === "number" ? r.quietWindowSnrDb : r && r.quietWindowSnrDb === "inf" ? Infinity : null);
  const cur = find("reverb_tail", "mp5c-high");
  const prev = find("reverb_tail", "mp5c2-bandquiet-extreme") || find("reverb_tail", "mp5c2-extreme");
  const best =
    find("reverb_tail", "mp5c2-smooth-extreme") ||
    find("reverb_tail", "mp5c2-bandquiet-extreme") ||
    find("reverb_tail", "mp5c2-extreme");
  const fmt = (v) => (v === Infinity ? "∞ (quiet windows bit-exact)" : v === null ? "—" : `${v.toFixed(1)} dB`);
  let verdict = "vNext sub-block/per-band: insufficient data.";
  if (best && cur) {
    const bRisk = best.hissRisk, pRisk = prev ? prev.hissRisk : "?";
    verdict =
      `**Best vNext (hysteresis/lookahead) reaches reverb_tail hiss risk \`${bRisk}\`** ` +
      `(prev vNext \`${pRisk}\`, current MP5-C \`${cur.hissRisk}\`). ` +
      `Quiet-window SNR: MP5-C ${fmt(q(cur))} → prev vNext ${fmt(q(prev))} → best ${fmt(q(best))}. ` +
      `${bRisk === "low" ? "Headphone-clean on this fixture; size cost reported below. Noise shaping was tried and measured *worse* — see report." : bRisk === "medium" ? "Improved; size cost below." : "Improved but not yet clean."}`;
  }

  const P = VNEXT_PARAMS;
  let md = "# MP5-C Hiss Report\n\n";
  md += `> **TL;DR.** ${verdict}\n\n`;
  md += `_Generated ${generatedAt}. Synthetic fixtures + optional local reference. Hiss Risk from quiet-class SNR (low ≥40 · medium ≥25 · high ≥12 · severe <12 dB). No telemetry; no copyrighted audio committed._\n\n`;
  md += `**vNext sub-block params:** sub-block ${P.subBlockFrames} frames (~${(P.subBlockFrames / 44.1).toFixed(0)} ms); broadband-quiet peak < ${P.quietPeak}; per-band escalation when sub-block RMS < ${P.fragileRmsMax} and ${P.hfCutoffHz} Hz high-band peak in (${P.hfPresentMin}, ${P.hfFragileMax}). "Protected %" = share of samples coded losslessly (L = broadband-quiet, B = per-band fragile tail).\n\n`;

  md += "## Synthetic fixtures — hiss matrix\n\n";
  const fixtures = [...new Set(rows.map((r) => r.fixture))];
  md += "| Fixture | Mode | ×PCM | Full SNR | Quiet SNR | Tail SNR | Worst-1s quiet | Err flat | Protected % | Hiss risk |\n";
  md += "|---------|------|-----:|---------:|----------:|---------:|---------------:|---------:|------------:|:---------:|\n";
  for (const fx of fixtures) {
    for (const r of rows.filter((r) => r.fixture === fx)) {
      if (r.error) { md += `| ${fx} | ${r.mode} | error |||||||\n`; continue; }
      const prot = r.protectedSamplePct === null || r.protectedSamplePct === undefined ? "—" : `${r.protectedSamplePct}%`;
      md += `| ${fx} | ${r.mode} | ${num(r.ratioVsPcm, 3)} | ${num(r.fullSnrDb)} | ${num(r.quietWindowSnrDb)} | ${num(r.tailSnrDb)} | ${num(r.worstQuiet1sSnrDb)} | ${num(r.errorSpectralFlatness, 3)} | ${prot} | ${RISK_ICON[r.hissRisk] ?? r.hissRisk} |\n`;
    }
  }

  if (referenceResult) {
    md += "\n## Local reference — IS THIS A CULT? (MP5-L baseline as ground truth)\n\n";
    md += writeCompareReport(referenceResult).split("\n").slice(2).join("\n");
  } else {
    md += "\n## Local reference\n\n_Reference files not present this run — synthetic results only._\n";
  }
  md += "\n## How to read this\n\n";
  md += "- **Quiet/Tail SNR** and **HF floor** expose hiss that **Full SNR** hides.\n";
  md += "- **Error spectral flatness** near 1.0 means the error is broadband — i.e. audible hiss.\n";
  md += "- MP5-L is the clean anchor (bit-exact → low risk). MP5-C current presets should read high/severe on decaying material.\n";
  return md;
}
